language: node_js
install:
- 'npm i -g typescript mocha'
- 'yarn'
node_js:
- '12'
- '10'
- '8'
- '6'
after_success: 'npm run coveralls'
notifications:
  email:
    on_success: never
    on_failure: change
